### ISSUE TITLE
Footnotes cannot span multiple lines

### ISSUE THREAD

**Issue by subsetpark** [yogthos/markdown-clj#101]
Forgive me if I misunderstand, but I have footnotes that are written like this:

```
[^2]: 
  Here is the first line of my footnote.

  Here is a new paragraph within the same footnote.
```

The footnote is rendered as just the first line, and the second line is included in the body text.

**Comment by yogthos** [comment]
Yeah, the current implementation only handles single line footnotes. I think multiple line footnotes would be a reasonable improvement, however I won't have time to look at it in the near future. If you'd be interested in trying to do a PR for it in the meantime, I'd be happy to provide some guidance with that.

**Comment by mrjin** [comment]
I think that this problem is due to the function `parse-footnotes` defined in markdown.core. As the function always read **one line** from the (stream/buffered)reader and pass it to the parse-footnote-link, the parse-footnote-link won't handle the footnotes with multiply lines correctly.

In my opinion, I think that one solution to this is to pre-process the input string/file to find out the footnote blocks rather than footnote lines, and then pass them as parameter to the `function parse-footnote-link`.

**Comment by yogthos** [comment]
Yeah, I think that would be simplest approach. Right now there's already some preprocessing being done for the reference links, so maybe that can be generalized. This would also allow for custom preprocessors to be supplied by the user as well.

**Comment by mrjin** [comment]
So you mean that there should be a preprocessing in a more generic way so that it can handle multiple lines for both reference and footnote?  And the preprocessing takes place before parse-footnote and parse-reference?

**Comment by mrjin** [comment]
Is there any documents for this project that is useful for contributing coding such as documentary, requirements or coding styles?

**Comment by yogthos** [comment]
Currently there are preprocessors for [references, footnotes, and metadata](https://github.com/yogthos/markdown-clj/blob/e85aedc7f5693a32084a1d4561064c8ec08a44c9/src/clj/markdown/core.clj#L77), all of these are run before the parser is engaged. So it might make sense to generalize that a bit. Perhaps the options map could have a `:prerocessors` key that points to a vector of preprocessor functions that should be run on the input before sending it to the parser.

For the footnotes fix itself, it looks like you'd just have to update the [parse-footnotes](https://github.com/yogthos/markdown-clj/blob/e85aedc7f5693a32084a1d4561064c8ec08a44c9/src/clj/markdown/core.clj#L44) function. It uses a `line-seq` at the moment, so that would have to be replaced with something more intelligent.

There isn't really any documentation regarding contributing. I'd just mostly recommend following the general Clojure style and using the current code as reference.

**Comment by mrjin** [comment]
Just changing the parse-footnote seems to result in one problem.
For example:
```
[^2]: 
    Here is the first line of my footnote.

    Here is a new paragraph within the same footnote.
```
If we correctly fix the parse-footnote, the third line 
```
    Here is a new paragraph within the same footnote.
```
may be regarded as code blocks once the length of the blank before the sentence is bigger than 3.

**Comment by yogthos** [comment]
I was thinking of aggregating the paragraphs into a single line in `parse-footnote`, so by the time it gets to the parser there's no confusion.
