### ISSUE TITLE
Unexpected empty paragraph after footer

### ISSUE THREAD

**Issue by whitecoop** [yogthos/markdown-clj#111]
Is the empty `<p></p>` after the `</footer>` expected behavior?

```clojure
(md->html "> Quote text\n>- Author Name\n\nA normal paragraph")
;; => "<blockquote><p> Quote text </p><footer> Author Name</footer><p></p></blockquote><p>A normal paragraph</p>"
```

Looks like it has to do with the double newlines after the footer, since these work as expected:

```clojure
(md->html "> Quote text\n>- Author Name\nA normal paragraph")
;; => "<blockquote><p> Quote text </p><footer> Author Name</footer><p>A normal paragraph </p></blockquote>"
```

```clojure
(md->html "> Quote text\n\nA normal paragraph")
;; => "<blockquote><p> Quote text </p></blockquote><p>A normal paragraph</p>"
```

**Comment by yogthos** [comment]
That does look like a bug in parsing the the footer content.

**Comment by GoranZic** [comment]
I am looking into this.
And from the short analysis I can see that the problem lies in blockquote function in markdown.transformers. 
Here is the the distilled example string which demonstrated the problem
` ">\n>- Author Name\n"`
generates
`<blockquote><p> </p><footer> Author Name</footer><p></p></blockquote>`

So it's not so much a problem of double new lines but simply a problem when footer is the last element.
This is because each conditional in the blockquote function opens a paragraph tag when it's done. So when footer is last in the blockquote it opens a new p tag and closing blockquote tag will close it. Just removing the opening p tag from end of footer won't cut it, because any following content expects to have an opened p tag.

I am proposing a more context sensitive way of opening and closing of p tags within blockquote.  I'll try to work out an elegant way, and create a pull request.

**Comment by yogthos** [comment]
Just pushed out a new version with the fix.

**Comment by whitecoop** [comment]
I'm still running into the same `<p></p>` after the footer with `0.9.91`.

```clojure
(md->html "> Quote text\n>- Author Name\n\nA normal paragraph")
;;=> "<blockquote><p> Quote text </p><footer> Author Name</footer><p></p></blockquote><p>A normal paragraph</p>"
```

**Comment by GoranZic** [comment]
I haven't been able to reproduce this. I pulled the code from the master, and tried the same example and got
`"<blockquote><p> Quote text </p><footer> Author Name</footer></blockquote><p>A normal paragraph</p>"

the only difference perhaps is that I didn't try the clojurescript version but the clojure version, but it should be the same it uses the same functions. Could you just double check you've pulled the new version.

**Comment by yogthos** [comment]
@whitecoop have you tried doing a clean to make sure the project doesn't have any stale artifacts?

**Comment by whitecoop** [comment]
I just needed to clean. Sorry about that.

**Comment by yogthos** [comment]
great to hear
